name: CI (Linux)

on: [push, pull_request]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: check build (async)
        run: cargo check --all --bins --examples --tests

      - name: tests (async)
        timeout-minutes: 40
        run: cargo test --all --no-fail-fast -- --nocapture

      - name: check build (is_sync)
        run: cargo check --features=is_sync --all --bins --examples --tests

      - name: tests (is_sync)
        timeout-minutes: 40
        run: cargo test --features=is_sync --all --no-fail-fast -- --nocapture

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: doc (async)
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --all --no-deps

      - name: doc (is_sync)
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --all --no-deps --features=is_sync

  publish:
    name: Publish Package
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: login
        env:
          SUPER_SECRET: ${{ secrets.CARGO_TOKEN }}
        run: cargo login "$SUPER_SECRET"

      - name: publish
        run: cargo publish
